name: Deploy Angular SSR to Azure Web App - Play

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear cached Azure CLI accounts
        run: az account clear

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build SSR app
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Zip SSR build for deployment
        run: zip -r release.zip dist/play

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AABE95094EA14C4CBEC936E463385811 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A507EADBC2649789C86ECEDAEDE3373 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA726858B51E401FB4DC4D0A74DBEB84 }}


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Playze-test'
          slot-name: 'Production'
          package: dist/play

      - name: Set startup command
        run: az webapp config set --name Playze-test --resource-group Playze_group --startup-file "node server/server.mjs"



